20220602/zhonghui/courses/urls.py
from django.urls import path
from . import views

app_name = "courses"

urlpatterns = [
    path('index', views.index, name="index"),
    path('add/', views.create, name="create"),
    path('update/<str:name>', views.update, name="update"),
    path('delete/<str:name>', views.delete, name="delete")
]

20220602/zhonghui/zhonghui/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from courses import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'courses/', include('courses.urls', namespace='courses')),
    re_path(r'^$', views.index)
]

20220602/zhonghui/courses/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    nickname=models.CharField(max_length=30,primary_key=True,db_index=True,verbose_name='昵称')
    introduction=models.TextField(default="这个老师很懒，没有介绍....",verbose_name='简介')
    fans=models.PositiveIntegerField(default=0,verbose_name='粉丝')
    create_at=models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    update_at = models.DateTimeField(auto_now=True,verbose_name='更新时间')

    class Meta:
        db_table='teacher'
        verbose_name='讲师信息表'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.nickname

class Course(models.Model):
    title=models.CharField(max_length=100,primary_key=True,db_index=True,verbose_name='课程名')
    teacher=models.ForeignKey(Teacher,on_delete=models.CASCADE,verbose_name='教师')
    type=models.SmallIntegerField(choices=((1,'后端开发'),(2,'数据挖掘'),(0,'其它')),default=0,verbose_name='课程类型')
    price=models.PositiveSmallIntegerField(verbose_name='价格')
    volume=models.BigIntegerField(verbose_name='销量')
    online=models.DateField(verbose_name='上线时间')
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新时间")

    class Meta:
        db_table='courses'
        verbose_name='课程信息表'
        verbose_name_plural = verbose_name
    def __str__(self):
        return f"{self.get_type_display()}--{self.title}"



class Student(models.Model):
    """学生信息表"""
    nickname=models.CharField(max_length=30,primary_key=True,db_index=True,verbose_name="昵称")
    course=models.ManyToManyField(Course,verbose_name="课程")#多对多关系
    age=models.PositiveSmallIntegerField(verbose_name="年龄")
    gender=models.SmallIntegerField(choices=((1,'男'),(2,'女'),(0,'保密')),default=0,verbose_name="性别")
    study_time=models.PositiveIntegerField(default="0",verbose_name="学习时长(h)")
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新时间")

    class Meta:
        db_table='student'
        verbose_name = '学生信息表'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.nickname


class TeacherAssistant(models.Model):
    nickname=models.CharField(max_length=30,primary_key=True,db_index=True,verbose_name="昵称")
    teacher=models.OneToOneField(Teacher,null=True,blank=True,on_delete=models.SET_NULL,verbose_name="讲师")
    hobby=models.CharField(max_length=100,null=True,blank=True,verbose_name="爱好")
    created_at=models.DateTimeField(auto_now_add=True,verbose_name="创建时间")
    updated_at=models.DateTimeField(auto_now=True,verbose_name="更新时间")

    class Meta:
        db_table='teacher_assistant'
        verbose_name = '助教信息表'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.nickname

20220602/zhonghui/courses/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Teacher, Course, Student


# Create your views here.
def index(request):
    teachers = Teacher.objects.all()

    return render(request, 'course.html', {'teachers': teachers})


def create(request):
    if request.method == 'POST':
        nickname = request.POST.get('nickname', '')
        introduce = request.POST.get('introduce', '')
        fans = request.POST.get('fans', 0)
        teacher = Teacher()
        teacher.nickname = nickname
        teacher.introduction = introduce
        teacher.fans = int(fans)
        teacher.save()
        return redirect('/courses/index')

    return render(request, 'add.html')


def update(request, name):
    if request.method == 'GET':
        teacher = Teacher.objects.filter(nickname=name)

        return render(request, 'update.html', {'teacher': teacher[0]})
    if request.method == 'POST':
        introduce = request.POST.get('introduce', '')
        fans = request.POST.get('fans', 0)
        Teacher.objects.filter(nickname=name).update(
            introduction=introduce,
            fans=fans
        )
        return redirect(reverse('courses:index'))


def delete(request, name):
    Teacher.objects.get(nickname=name).delete()
    return redirect(reverse('courses:index'))

20220602/zhonghui/templates/add.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <style>
        body {
            padding: 0;
            margin: 0;
            background: url("/static/img/cour.png");
        }

        form {
            width: 1020px;
            margin: 100px auto;
            border: 1px solid silver;
            box-shadow: 2px 2px 4px slategray;
            background-color: rgba(0, 0, 0, 0.3);
            color: white;
        }

        h1 {
            font-family: 仿宋, serif;
            text-align: center;
        }

        hr {
            width: 960px;
        }

        .form-group {
            margin: 30px;
        }

        .btn {
            width: 960px;
            margin: 30px;

        }
    </style>
</head>
<body>
<form action="{% url 'courses:create' %}" method="post">
    {% csrf_token %}
    <h1>添加教师</h1>
    <hr>
    <div class="form-group">
        <label for="exampleInputEmail1">昵称：</label>
        <input type="text" class="form-control" id="exampleInputEmail1" name="nickname">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail2">简介：</label>
        <input type="text" class="form-control" id="exampleInputEmail2" name="introduce">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail3">粉丝数：</label>
        <input type="text" class="form-control" id="exampleInputEmail3" name="fans">
    </div>
    <button type="submit" class="btn btn-primary table_b">添加</button>
</form>
</body>
</html>

20220602/zhonghui/templates/course.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <style>
        @import url('/static/css/course.css');
    </style>
</head>
<body>
    <h1>教师管理</h1>
    <table class="table table-bordered num1" >
        <tr>
<!--            <th>编号</th>-->
            <th>昵称</th>
            <th>简介</th>
            <th>粉丝数</th>
            <th>功能</th>
        </tr>
        {% for teacher in teachers %}
            <tr>
                <!--            <td style="width: 80px">1</td>-->
                <td style="width: 100px">{{ teacher.nickname }}</td>
                <td style="width: 600px;text-align: left;text-indent: 2px;">{{ teacher.introduction }}</td>
                <td style="width: 100px;">{{ teacher.fans }}</td>
                <td>
                    <a href="{% url 'courses:update' teacher.nickname %}">
                        <button type="button" class="btn btn-primary ">修改</button>
                    </a>
                    <a href="{% url 'courses:delete' teacher.nickname%}">
                        <button type="button" class="btn btn-primary ">删除</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="5">
                <a href="{% url 'courses:create' %}">
                   <button type="button" class="btn btn-primary table_b">添加信息</button>
                </a>
            </td>

        </tr>

    </table>
</body>
</html>

20220602/zhonghui/templates/update.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <style>
        body {
            padding: 0;
            margin: 0;
            background: url("/static/img/cour.png");
        }

        form {
            width: 1020px;
            margin: 100px auto;
            border: 1px solid silver;
            box-shadow: 2px 2px 4px slategray;
            background-color: rgba(0, 0, 0, 0.3);
            color: white;
        }

        h1 {
            font-family: 仿宋, serif;
            text-align: center;
        }

        hr {
            width: 960px;
        }

        .form-group {
            margin: 30px;
        }

        .btn {
            width: 960px;
            margin: 30px;

        }
    </style>
</head>
<body>
<form action="/courses/update/{{ teacher.nickname }}" method="post">
    {% csrf_token %}
    <h1>信息修改</h1>
    <hr>
    <div class="form-group">
        <label for="exampleInputEmail1">昵称：</label>
        <input type="text" class="form-control" id="exampleInputEmail1" name="nickname" value="{{ teacher.nickname }}" readonly>
    </div>
    <div class="form-group">
        <label for="exampleInputEmail2">简介：</label>
        <input type="text" class="form-control" id="exampleInputEmail2" name="introduce" value="{{ teacher.introduction }}">
    </div>
    <div class="form-group">
        <label for="exampleInputEmail3">粉丝数：</label>
        <input type="text" class="form-control" id="exampleInputEmail3" name="fans" value="{{ teacher.fans }}">
    </div>
    <button type="submit" class="btn btn-primary table_b">修改</button>
</form>
</body>
</html>